//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SparkOperator) DeepCopyInto(out *SparkOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SparkOperator.
func (in *SparkOperator) DeepCopy() *SparkOperator {
	if in == nil {
		return nil
	}
	out := new(SparkOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SparkOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SparkOperatorList) DeepCopyInto(out *SparkOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SparkOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SparkOperatorList.
func (in *SparkOperatorList) DeepCopy() *SparkOperatorList {
	if in == nil {
		return nil
	}
	out := new(SparkOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SparkOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SparkOperatorSpec) DeepCopyInto(out *SparkOperatorSpec) {
	*out = *in
	out.ManagementSpec = in.ManagementSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SparkOperatorSpec.
func (in *SparkOperatorSpec) DeepCopy() *SparkOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(SparkOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SparkOperatorStatus) DeepCopyInto(out *SparkOperatorStatus) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	in.ComponentReleaseStatus.DeepCopyInto(&out.ComponentReleaseStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SparkOperatorStatus.
func (in *SparkOperatorStatus) DeepCopy() *SparkOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(SparkOperatorStatus)
	in.DeepCopyInto(out)
	return out
}
