coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

flags:
  unit:
    paths:
      - "!test/e2e/"
      - "!test/e2e/rhoai/"
  e2e-kustomize:
    paths:
      - "!test/e2e/"

comment:
  layout: "reach,diff,flags,files"
  behavior: default

