# Build the module operator binary
ARG GO_BUILDER_IMAGE=registry.access.redhat.com/ubi9/go-toolset:1.25.7@sha256:2830e4bd1c394ed506c00a9abbb4d00445e2e72e8ef4e3cd51e0da0db66dee12
ARG BASE_IMAGE=registry.access.redhat.com/ubi9/ubi-minimal:9.6@sha256:34880b64c07f28f64d95737f82f891516de9a3b43583f39970f7bf8e4cfa48b7

################################################################################
# Stage 1: Build the Go module operator binary
################################################################################
FROM ${GO_BUILDER_IMAGE} AS builder

USER 0
WORKDIR /go/src/github.com/opendatahub-io/spark-operator-module

COPY spark-operator-module/go.mod  go.mod
COPY spark-operator-module/go.sum  go.sum
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY spark-operator-module/cmd/spark-operator-module/ cmd/spark-operator-module/
COPY spark-operator-module/pkg/              pkg/

ARG TARGETARCH
ARG GOTAGS="distro"

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=1 GOOS=linux GOARCH=${TARGETARCH} GOEXPERIMENT=strictfipsruntime go build -tags "${GOTAGS},strictfipsruntime" -a -o manager ./cmd/spark-operator-module

# Collect Spark workload operator manifests from this repo
COPY spark-operator-module/hack/  hack/
COPY config/                      ../config/
RUN bash hack/get_spark_manifests.sh

################################################################################
# Stage 2: Runtime image
################################################################################
FROM ${BASE_IMAGE}

USER 0

RUN useradd spark -m -u 1000

COPY --from=builder /go/src/github.com/opendatahub-io/spark-operator-module/manager /manager
COPY --from=builder /go/src/github.com/opendatahub-io/spark-operator-module/opt/manifests/ /opt/manifests-template/

USER 1000:1000
ENTRYPOINT ["/manager"]

LABEL com.redhat.component="odh-spark-operator-module-controller" \
      name="managed-open-data-hub/odh-spark-operator-module-controller-rhel9" \
      description="This image contains the Spark Operator Module controller. It manages the lifecycle of the Spark workload operator as an ODH component, handling installation, upgrades, and configuration via the SparkOperator custom resource." \
      summary="odh-spark-operator-module-controller" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-spark-operator-module-controller" \
      io.k8s.description="odh-spark-operator-module-controller" \
      distribution-scope="public" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"
