apiVersion: v1
kind: Service
metadata:
  name: spark-connect-service
  namespace: redhat-ods-applications
  labels:
    app.kubernetes.io/part-of: sparkoperator
spec:
  type: ClusterIP
  selector:
    sparkoperator.k8s.io/connect-name: spark-connect
    spark-role: connect-server
  ports:
    - name: spark-connect
      port: 15002
      targetPort: 15002
      protocol: TCP
