apiVersion: v1
kind: Secret
metadata:
  name: spark-s3-credentials
  namespace: spark-test
type: Opaque
stringData:
  # S3 access credentials (env var names used by all S3-compatible providers)
  AWS_ACCESS_KEY_ID: YOUR_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: YOUR_SECRET_ACCESS_KEY

  # Optional: Some S3 providers use regions, others don't
  # AWS_REGION: us-east-2
